### ISSUE TITLE
user32: cannot open shared object file: No such file or directory (Fiddle::DLError)

### ISSUE THREAD

**Issue by grun00** [erinata/auto_click#11]
Hey! 

I'm trying to add this library to a small project I have and I'm having the following error when I try to run it:

```
/home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:61:in `initialize': user32: cannot open shared object file: No such file or directory (Fiddle::DLError)
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:61:in `new'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:61:in `dlopen'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle/import.rb:86:in `block in dlload'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle/import.rb:77:in `collect'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle/import.rb:77:in `dlload'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/auto_click-0.5.9/lib/auto_click/user32.rb:3:in `<module:User32>'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/auto_click-0.5.9/lib/auto_click/user32.rb:1:in `<top (required)>'
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/grun/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/auto_click-0.5.9/lib/auto_click.rb:4:in `<top (required)>'
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from lib/main.rb:5:in `<main>'
<internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- auto_click (LoadError)
        from <internal:/home/grun/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from lib/main.rb:5:in `<main>'
```

It's a pure ruby project with very few dependencies.
Here's my `Gemfile` and `Gemfile.lock`:

```
source 'https://rubygems.org'

gem 'pry'
gem 'auto_click'
gem 'watir'
gem 'fiddle'
```

```
GEM
  remote: https://rubygems.org/
  specs:
    auto_click (0.5.9)
    childprocess (4.1.0)
    coderay (1.1.3)
    fiddle (1.1.0)
    method_source (1.0.0)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    regexp_parser (2.2.0)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    watir (7.1.0)
      regexp_parser (>= 1.2, < 3)
      selenium-webdriver (~> 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  auto_click
  fiddle
  pry
  watir

BUNDLED WITH
   2.2.15
```

Any ideas of what it might be?

**Comment by zsarge** [comment]
Just passing through, but I'm pretty sure that this library does not support Linux at this time. 

It seems that [it tries to](https://github.com/erinata/auto_click/blob/221b43995019a2ce63ccefbc16645fa4bf606193/lib/auto_click/user32.rb#L1-L3) simulate mouse events through User32, which is a [dll](https://en.wikipedia.org/wiki/Dynamic-link_library) for Windows specifically.
